import day11 from './index';

const example_input1 = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`;

describe('On Day 11', () =>{
    it(`part1`, ()=>{
        expect(day11.solveForPartOne(example_input1)).toBe('374');
    })
});
